config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show]

  match '/open', to: 'users#open', via: :post
  match '/close', to: 'users#close', via: :post
  

  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  extend FriendlyId
  friendly_id :org_name, use: :slugged

  def open!
    self.update_attribute(:open, true)
  end

  def close!
    self.update_attribute(:open, false)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:org_name, :description, :email, :password, :password_confirmation, :remember_me) }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to page_path('home') and return unless user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, except: [:show]

  def open
    current_user.open!
    redirect_to root_path
  end

  def close
    current_user.close!
    redirect_to root_path
  end

  def show
    @user = User.friendly.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="row">
  <div class="medium-6 columns small-centered text-center">
    <h1><%= current_user.org_name %></h1>
    <hr />
  </div>
</div>

<div class="row">
  <div class="medium-6 columns small-centered text-center">
    <% if current_user.open? %>
      <p>You're open!</p>
      <%= link_to "Be closed", close_path, method: :post, class: "button" %>
    <% else %>
      <p>You're closed.</p>
      <%= link_to "Be open", open_path, method: :post, class: "button" %>
    <% end %>
    <hr />
  </div>
</div>

<div class="row">
  <div class="medium-6 columns small-centered text-center">
    <p>Your org page:</p>
    <input type="text" value="<%= user_url(current_user) %>" onclick="this.select();" />
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><a href="#">We're here!</a></h1>
        </li>
         <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">
        <ul class="right">
          <li class="has-dropdown">
            <% if user_signed_in? %>
              <a href="#">Logged in as <%= current_user.email %></a>
              <ul class="dropdown">
                <li><%= link_to "Account settings", edit_user_registration_path %></li>
                <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
              </ul>
            <% else %>
              <li class="<%= controller.controller_name == 'sessions' ? 'active' : '' %>"><%= link_to "Log in", new_user_session_path %></li>
              <li class="<%= controller.controller_name == 'registrations' ? 'active' : '' %>"><%= link_to "Create an account", new_user_registration_path %></li>
            <% end %>
          </li>
        </ul>

      </section>
    </nav>

    <%= yield %>

  </body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en"}
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tag

  %body

    = yield

app/views/pages/home.html.erb
Sign up yo

app/views/users/show.html.haml
.row
  .medium-6.columns.small-centered.text-center
    %h1= @user.org_name
    %p= @user.description
    %hr

    - if @user.open?
      %p We're open! Swing by.
    - else
      %p We're closed. Check back later.